name: React App Deploy to Surge

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install dependencies
        run: npm i

      - name: Build React App
        run: yarn build && cd build && sudo cp index.html 200.html

      - name: Install Surge
        run: npm install --global surge

      - name: Deploy to Surge
        run: surge ./build shoe-store-react-router-v6.surge.sh --token ${{ secrets.SURGE_TOKEN }}
